FIX_REGISTRY={
    "RD001":{
        "fix_type":"trim_overshoot",
        "risk":"high",
        "auto_apply":False,
        "requires_approval":True,
        "implemented":False
    },
    "RD002":{
        "fix_type":"snap_endpoint",
        "risk":"high",
        "auto_apply":False,
        "requires_approval":True,
        "implemented":False
    },
    "RD003":{
        "fix_type":"remove_duplicate",
        "risk":"medium",
        "auto_apply":False,
        "requires_approval":True,
        "implemented":True
    },
    "RD004":{
        "fix_type":"make_valid",
        "risk":"low",
        "auto_apply":True,
        "requires_approval":False,
        "implemented":True
    },
    "RD005":{
        "fix_type":None,
        "risk":"high",
        "auto_apply":False,
        "requires_approval":True,
        "implemented":False
    },
    "BLD001":{
        "fix_type":"resolve_overlap",
        "risk":"high",
        "auto_apply":False,
        "requires_approval":True,
        "implemented":False
    },
    "BLD002":{
        "fix_type":"remove_duplicate",
        "risk":"medium",
        "auto_apply":False,
        "requires_approval":True,
        "implemented":True
    },
    "BLD003":{
        "fix_type":"make_valid",
        "risk":"low",
        "auto_apply":True,
        "requires_approval":False,
        "implemented":True
    },
    "BLD004":{
        "fix_type":None,
        "risk":"high",
        "auto_apply":False,
        "requires_approval":True,
        "implemented":False
    },
    "GIS001":{
        "fix_type":"transform_processing_crs",
        "risk":"high",
        "auto_apply":False,
        "requires_approval":True,
        "implemented":False
    },
    "GIS002":{
        "fix_type":None,
        "risk":"high",
        "auto_apply":False,
        "requires_approval":True,
        "implemented":False
    },
    "GIS003":{
        "fix_type":None,
        "risk":"medium",
        "auto_apply":False,
        "requires_approval":True,
        "implemented":False
    },
    "GIS004":{
        "fix_type":None,
        "risk":"medium",
        "auto_apply":False,
        "requires_approval":True,
        "implemented":False
    },
    "GIS005":{
        "fix_type":None,
        "risk":"medium",
        "auto_apply":False,
        "requires_approval":True,
        "implemented":False
    }
}

def get_fix_definition(rule_id:str)->dict|None:
    return FIX_REGISTRY.get(rule_id)