[project]
name = "meyaar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "chromadb>=1.5.9",
    "datasets>=5.0.1",
    "faiss-cpu>=1.15.0",
    "fastapi>=0.141.1",
    "folium>=0.20.0",
    "geoalchemy2>=0.20.0",
    "geopandas>=1.1.4",
    "groq>=1.7.0",
    "jinja2>=3.1.6",
    "jupyter>=1.1.1",
    "kaleido>=1.4.0",
    "langchain-experimental>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "langgraph>=1.2.11",
    "llama-index-core>=0.14.24",
    "llama-index-embeddings-huggingface>=0.8.0",
    "llama-index-postprocessor-sbert-rerank>=0.6.0",
    "llama-index-vector-stores-chroma>=0.6.0",
    "matplotlib>=3.11.1",
    "moondream>=2.1.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "playwright>=1.62.0",
    "plotly>=7.0.0",
    "psycopg2-binary>=2.9.12",
    "pyarrow>=25.0.1",
    "pymupdf>=1.28.2",
    "pyogrio>=0.13.0",
    "pypdf>=6.17.0",
    "pyproj>=3.7.2",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "rank-bm25>=0.2.2",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=6.0.1",
    "shapely>=2.1.2",
    "sqlalchemy>=2.0.52",
    "streamlit>=1.63.0",
    "streamlit-folium>=0.27.4",
    "torch>=2.14.0",
    "transformers>=5.16.1",
    "uvicorn>=0.52.4",
    "xgboost>=3.4.1",
]
