"use client";

import { useState } from "react";
import { changePassword, getMe, logout } from "@/lib/api";
import type { AuthUser } from "@/types/analysis";

export default function FirstLoginPassword({ user, onComplete, onCancel }: { user: AuthUser; onComplete: (user: AuthUser) => void; onCancel: () => void }) {
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (newPassword !== confirmation) { setError("New passwords do not match."); return; } setLoading(true); try { await changePassword(currentPassword, newPassword); onComplete(await getMe()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Password could not be changed."); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-[#eef5ff] p-5"><section className="w-full max-w-md rounded-3xl border border-blue-100 bg-white p-7 shadow-xl"><p className="text-xs font-black tracking-[.2em] text-blue-600">MEYAAR</p><h1 className="mt-3 text-2xl font-extrabold text-[#071c33]">Create your private password</h1><p className="mt-2 text-sm leading-6 text-slate-500">Welcome {user.name}. For security, replace the temporary password before accessing the platform.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-semibold">Temporary password<input required type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3"/></label><label className="block text-sm font-semibold">New password<input required minLength={8} type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3"/></label><label className="block text-sm font-semibold">Confirm password<input required minLength={8} type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3"/></label>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-blue-600 py-3 font-bold text-white disabled:bg-slate-400">{loading ? "Saving..." : "Set password and continue"}</button></form><button type="button" onClick={async () => { await logout(); onCancel(); }} className="mt-4 w-full text-sm font-bold text-slate-500">Sign out</button></section></main>;
}
