"use client";

import { useEffect, useState } from "react";
import { changePassword, listTeams } from "@/lib/api";
import type { AuthUser, TeamMembership } from "@/types/analysis";

export default function ProfilePanel({ user }: { user: AuthUser }) {
  const [teams, setTeams] = useState<TeamMembership[]>([]);
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmation, setConfirmation] = useState("");
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState<{ text: string; error: boolean } | null>(null);
  useEffect(() => { listTeams().then(setTeams).catch(() => setTeams([])); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setNotice(null); if (newPassword !== confirmation) { setNotice({ text: "New passwords do not match.", error: true }); return; } setSaving(true); try { await changePassword(currentPassword, newPassword); setCurrentPassword(""); setNewPassword(""); setConfirmation(""); setNotice({ text: "Password changed successfully.", error: false }); } catch (reason) { setNotice({ text: reason instanceof Error ? reason.message : "Password could not be changed.", error: true }); } finally { setSaving(false); } }
  return <div className="grid items-start gap-5 xl:grid-cols-[1fr_420px]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-4"><div className="flex size-16 items-center justify-center rounded-full bg-blue-600 text-2xl font-black text-white">{user.name.trim().charAt(0).toUpperCase()}</div><div><h2 className="text-2xl font-extrabold text-[#071c33]">{user.name}</h2><p className="text-sm text-slate-500">Personal account information</p></div></div><dl className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><dt className="text-xs text-slate-500">Email</dt><dd className="mt-1 break-all font-bold">{user.email}</dd></div><div className="rounded-xl bg-slate-50 p-4"><dt className="text-xs text-slate-500">Current team</dt><dd className="mt-1 font-bold">{user.team_name ?? "No active team"}</dd></div><div className="rounded-xl bg-slate-50 p-4"><dt className="text-xs text-slate-500">Current role</dt><dd className="mt-1 font-bold capitalize">{user.role === "leader" ? "Team Leader" : user.role ?? "—"}</dd></div><div className="rounded-xl bg-slate-50 p-4"><dt className="text-xs text-slate-500">Teams</dt><dd className="mt-1 font-bold">{teams.length}</dd></div></dl><h3 className="mt-6 font-bold">My teams</h3><div className="mt-3 flex flex-wrap gap-2">{teams.map((team) => <span key={team.team_id} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${team.team_id === user.team_id ? "border-blue-300 bg-blue-50 text-blue-700" : "border-slate-200 text-slate-600"}`}>{team.name} · {team.role === "leader" ? "Team Leader" : team.role}</span>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold text-[#071c33]">Change password</h2><p className="mt-1 text-sm text-slate-500">Other active sessions will be signed out.</p><form onSubmit={submit} className="mt-5 space-y-4">{[["Current password", currentPassword, setCurrentPassword], ["New password", newPassword, setNewPassword], ["Confirm new password", confirmation, setConfirmation]].map(([label, value, setter]) => <label key={label as string} className="block text-sm font-semibold">{label as string}<input required minLength={label === "Current password" ? 1 : 8} type="password" value={value as string} onChange={(event) => (setter as (value: string) => void)(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-blue-500"/></label>)}{notice && <p className={`rounded-xl p-3 text-sm ${notice.error ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{notice.text}</p>}<button disabled={saving} className="w-full rounded-xl bg-blue-600 py-3 text-sm font-bold text-white disabled:bg-slate-400">{saving ? "Saving..." : "Update password"}</button></form></section></div>;
}
